### ISSUE TITLE
bmcd panics on restarting

### ISSUE THREAD

**Issue by werdnum** [turing-machines/BMC-Firmware#135]
**Describe the bug**

```
# /etc/init.d/S94bmcd reload
Stopping bmcd: OK
2023-11-03T05:06:22.635Z INFO  [bmcd] exiting bmcd
Starting bmcd...
# 2023-11-03T05:06:23.371Z INFO  [bmcd] Turing Pi 2 BMC Daemon v2.0.0

#
# thread 'main' panicked at 'source slice length (0) does not match destination slice length (16384)', src/utils/ring_buf.rs:22:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'source slice length (0) does not match destination slice length (16384)', src/utils/ring_buf.rs:22:33
```

With full backtrace:

```
thread 'main' panicked at 'source slice length (0) does not match destination slice length (16384)', src/utils/ring_buf.rs:22:33
stack backtrace:
   0:   0x7681bc - <unknown>
   1:   0x62b08c - <unknown>
   2:   0x7647e0 - <unknown>
   3:   0x767fe4 - <unknown>
   4:   0x7697f4 - <unknown>
   5:   0x769524 - <unknown>
   6:   0x769e4c - <unknown>
   7:   0x769c00 - <unknown>
   8:   0x768820 - <unknown>
   9:   0x769998 - <unknown>
  10:   0x4808cc - <unknown>
  11:   0x480eb0 - <unknown>
  12:   0x6346f4 - <unknown>
  13:   0x5b6024 - <unknown>
  14:   0x59e748 - <unknown>
  15:   0x5967c4 - <unknown>
  16:   0x5a8700 - <unknown>
  17:   0x5cc338 - <unknown>
  18:   0x52334c - <unknown>
  19:   0x585f70 - <unknown>
  20:   0x5ae1c8 - <unknown>
  21:   0x532ba8 - <unknown>
  22:   0x54d4fc - <unknown>
  23:   0x5860c4 - <unknown>
  24:   0x536734 - <unknown>
  25:   0x585848 - <unknown>
  26:   0x5ae314 - <unknown>
  27:   0x5715bc - <unknown>
  28:   0x5775ac - <unknown>
  29:   0x5e875c - <unknown>
  30:   0x5e879c - <unknown>
  31:   0x75ce20 - <unknown>
  32:   0x5e8788 - <unknown>
  33: 0xb6a49868 - <unknown>
  34: 0xb6a49970 - __libc_start_main
thread 'main' panicked at 'source slice length (0) does not match destination slice length (16384)', src/utils/ring_buf.rs:22:33
stack backtrace:
   0:   0x7681bc - <unknown>
   1:   0x62b08c - <unknown>
   2:   0x7647e0 - <unknown>
   3:   0x767fe4 - <unknown>
   4:   0x7697f4 - <unknown>
   5:   0x769524 - <unknown>
   6:   0x769e4c - <unknown>
   7:   0x769c00 - <unknown>
   8:   0x768820 - <unknown>
   9:   0x769998 - <unknown>
  10:   0x4808cc - <unknown>
  11:   0x480eb0 - <unknown>
  12:   0x6346f4 - <unknown>
  13:   0x5b6024 - <unknown>
  14:   0x59e748 - <unknown>
  15:   0x5967c4 - <unknown>
  16:   0x5a8700 - <unknown>
  17:   0x5cc338 - <unknown>
  18:   0x52334c - <unknown>
  19:   0x585f70 - <unknown>
  20:   0x5ae1c8 - <unknown>
  21:   0x532ba8 - <unknown>
  22:   0x54d4fc - <unknown>
  23:   0x5860c4 - <unknown>
  24:   0x536734 - <unknown>
  25:   0x585848 - <unknown>
  26:   0x5ae314 - <unknown>
  27:   0x5715bc - <unknown>
  28:   0x5775ac - <unknown>
  29:   0x5e875c - <unknown>
  30:   0x5e879c - <unknown>
  31:   0x75ce20 - <unknown>
  32:   0x5e8788 - <unknown>
  33: 0xb6a49868 - <unknown>
  34: 0xb6a49970 - __libc_start_main
```

**To Reproduce**

On my board, `/etc/init.d/S94bmcd  reload` then go to http://turingpi.local

**Expected behavior**

Should be obvious.

**Screenshots**

**Versions**
linux version= Linux turingpi 5.4.61 #1 SMP PREEMPT Wed Nov 1 19:39:23 UTC 2023 armv7l GNU/Linux
bmc version= 2.0.0-RC1

**Additional context**

**Comment by svenrademakers** [comment]
@ruslashev, could you take a look at this one. Its similar to what I was observing as well
